# A configuration example for the subscription converter
# Contributor: tindy2013


[common]
;allows insecure TLS (SSL) connection
tls13=false
default_exclude_params=flag|mnc|mcc|test|ignore
default_include_remarks=
default_exclude_remarks=

;subscription link update settings
;update interval in hours, default 72
update_interval=24
;pre-check update, default true
pre_check_update=true
;strict mode, default false
;if strict mode enabled, only the following nodes will be converted
default_strict_mode=false

;performance settings
;max concurrency threads when fetch subscription links, default 8
concurrent=32
;allow to use Cache, default false
allow_cache=false

;artificial settings for nodes convert
generate_asset=true

;generator scope
expired_interval=72

;custom group name
default_custom_group=🎯 全球直连|🍎 苹果服务|Ⓜ️ 微软服务|📲 电报信息|🌍 国外媒体|🌏 国内媒体|🎥 NETFLIX|🛑 全球拦截|🔰 节点选择|🐟 漏网之鱼
