name: Aggregator Auto Run

on:
  schedule:
    - cron: '0 22,4,10,16 * * *'
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt pyyaml

      - name: Download clash
        run: |
          mkdir -p clash
          curl -sL -o clash/clash-linux-amd https://github.com/wzdnzd/aggregator/raw/main/clash/clash-linux-amd
          chmod +x clash/clash-linux-amd

      - name: Run
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: python subscribe/process.py -s my-config.json -r 3 -t 5000

      - uses: actions/upload-artifact@v4
        with:
          name: node-output
          path: output/
          retention-days: 7
